### ISSUE TITLE
UnboundLocalError: local variable 'labels' referenced before assignment

### ISSUE THREAD

**Issue by StephaneLu** [GGiecold/Concurrent_AP#2]
Hi,
I am having an issue running your code on mac osx : 

> Traceback (most recent call last):
>   File "/usr/local/bin/concurrent_AP", line 9, in <module>
>     load_entry_point('Concurrent-AP==1.4', 'console_scripts', 'Concurrent_AP')()
>   File "/Library/Python/2.7/site-packages/Concurrent_AP.py", line 1416, in main
>     output_clusters(labels, cluster_centers_indices)
> UnboundLocalError: local variable 'labels' referenced before assignment

Any hint ?

**Comment by GGiecold-zz** [comment]
Hi,

Could you please share more information regarding the circumstances
surrounding  this issue?

Are you running Concurrent_AP from the command line, by calling
'Concurrent_AP file_path', with file_path referring to a tab-separated
dataset with each row standing for a sample?

Just this morning, I ran this module both on a laptop running Fedora-Linux
and on my MacBook; I could not reproduce the error message you're reporting.

Kind regards,

Gregory

**Comment by StephaneLu** [comment]
Hi Gregory,
thank you for your work :+1: , 
I fixed the issue by changing the np.savetxt() with the proper delimiter. '\t'
I was trying to load the hdf5 file prior to create it ...
I disabled the  `fh = NamedTemporaryFile('w', delete = False, dir = './',suffix = '.h5')` to ba able to load it in the future.
I made several other changes on memory because osx does not support  '/proc/meminfo' :
     memory() : `psutil.phymem_usage().free / used`, it seems to work so far ...
     get_chunksize() : as max(xxxxx, mem_free \* 0.07)

Regards
Stéphane

**Comment by GGiecold-zz** [comment]
Hello Stéphane,

Glad to hear everything is in order!

Your message made me realize that the documentation to Concurrent_AP didn't
emphasize enough that it only accepts tab-separated data files. I've edited
its PyPI page accordingly (the Github page had been edited separately and
was clearer in this regard). Thanks!

I'm swamped with work right now but I should change at some point the code
relying on /proc/meminfo. Some one trying to run DBSCAN_MULTIPLEX on
Windows had a similar problem a while ago.
Feel free to push the change you brought to get things working on OS X.

All the best with your programming endeavors,

Gregory

**Comment by lucapinello** [comment]
Hi @StephaneLu do you mind to share the changes? I have the same problems on my mac.

Thanks!
