### ISSUE TITLE
Its unable to read a CSV file and getting error 'xrange' is not defined?

### ISSUE THREAD

**Issue by arsalan993** [GGiecold/Concurrent_AP#5]
When i run this command on my dataset, dataset without index and header as per requirement, i get an error.

command = Concurrent_AP --preference -5.47 --v test1.csv 
ValueError: could not convert string to float: '-3.1327,-10.187999999999999,-1.0488,-3.0399,-0.43163,-0.061478,-2.9783,-0.4948,-0.81215,21.24,42.72,15.42'

while on command = Concurrent_AP --preference -5.47 --v iris_data.tsv 
    for i in xrange(N_processes):
NameError: name 'xrange' is not defined

**Comment by GGiecold-zz** [comment]
Use python 2.x.
